"""Создание таблиц Customer, Structure, Factory, Product, ProductType, Shipment

Revision ID: 2171ee488e8f
Revises: 200fdd84be7e
Create Date: 2024-04-19 14:32:11.692189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2171ee488e8f'
down_revision: Union[str, None] = '200fdd84be7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_structure',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=129), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('factory',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=129), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('customer',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=129), nullable=True),
    sa.Column('inn', sa.BigInteger(), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('mail', sa.VARCHAR(length=129), nullable=True),
    sa.Column('manager', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('structure', sa.VARCHAR(length=129), nullable=False),
    sa.ForeignKeyConstraint(['manager'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['structure'], ['business_structure.type'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('inn')
    )
    op.create_table('product_type',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product', sa.VARCHAR(length=256), nullable=False),
    sa.Column('product_type', sa.VARCHAR(length=256), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product'], ['product.name'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('product_type')
    )
    op.create_table('shipment',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('factory_name', sa.VARCHAR(length=129), nullable=False),
    sa.Column('delivery_address', sa.VARCHAR(length=256), nullable=True),
    sa.Column('time_on_site', sa.Time(), nullable=True),
    sa.Column('loading_time', sa.Time(), nullable=True),
    sa.Column('product_name', sa.VARCHAR(length=256), nullable=False),
    sa.Column('call_product_type', sa.VARCHAR(length=256), nullable=False),
    sa.Column('real_product_type', sa.VARCHAR(length=256), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('additional_equipment', sa.VARCHAR(length=256), nullable=True),
    sa.Column('payment', sa.VARCHAR(length=3), nullable=False),
    sa.Column('comment', sa.VARCHAR(length=256), nullable=True),
    sa.Column('supplier', sa.VARCHAR(length=256), nullable=True),
    sa.Column('consignee', sa.BigInteger(), nullable=False),
    sa.Column('consignee_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('manager', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['call_product_type'], ['product_type.product_type'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['consignee'], ['customer.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['factory_name'], ['factory.name'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manager'], ['user.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['product_name'], ['product.name'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['real_product_type'], ['product_type.product_type'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_table('shipment')
    op.drop_table('product_type')
    op.drop_table('customer')
    op.drop_table('product')
    op.drop_table('factory')
    op.drop_table('business_structure')
    # ### end Alembic commands ###
