"""проверка работы связи o-t-o

Revision ID: b94aefa9e0d7
Revises: ca79f856c0d9
Create Date: 2024-06-01 18:00:14.198582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b94aefa9e0d7'
down_revision: Union[str, None] = 'ca79f856c0d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
