"""Добавление поля name в таблицу Roles

Revision ID: ca79f856c0d9
Revises: ef398fde29ef
Create Date: 2024-06-01 17:42:28.005674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca79f856c0d9'
down_revision: Union[str, None] = 'ef398fde29ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('name', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'role', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_column('role', 'name')
    # ### end Alembic commands ###
